.PROGRAM temp()
  ; Program generated by RoboDK v5.6.8 for Kawasaki BX130X on 01/04/2024 15:37:29
  ; Using nominal kinematics.
  SPEED 100MM/S ALWAYS
;   TOOL TRANS(0,0,0,0,0,0)
 TOOL TRANS(72.114,193.386,512.986,90.566,45.001,1)
;   JMOVE #[-20,20,5,5,5,10]

  BASE NULL
.END
